// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlkkggyqluhqllycwtlp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impsa2tnZ3lxbHVocWxseWN3dGxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNTkwNDUsImV4cCI6MjA1NzkzNTA0NX0.WL2LG7R6dQHg26IunxJ0SV-NhJ8y7_5EeaOwNTnqAMQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);